# Generated by Django 3.1.12 on 2026-02-10 16:22

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('escudo', models.URLField(blank=True, max_length=500, null=True)),
                ('liga', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=20)),
                ('entrenador', models.CharField(max_length=100)),
                ('piscina', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='rankingWaterpolo.categoria')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'equipos',
            },
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('usuario_id', models.IntegerField()),
                ('puntuacion', models.IntegerField(help_text='Puntuación del 1 al 10')),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='rankingWaterpolo.team')),
            ],
            options={
                'verbose_name': 'Valoración',
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('usuario_id', models.IntegerField(default=1)),
                ('temporada', models.CharField(default='2025/2026', max_length=20)),
                ('equipos', models.ManyToManyField(related_name='rankings', to='rankingWaterpolo.Team')),
            ],
        ),
    ]
