# Generated by Django 3.1.12 on 2026-02-10 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('temporada', models.CharField(default='2024/25', max_length=50, verbose_name='Temporada')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categorias/', verbose_name='Logo/Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('escudo', models.URLField(blank=True, max_length=500, null=True)),
                ('liga', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=20)),
                ('entrenador', models.CharField(blank=True, max_length=100, null=True)),
                ('piscina', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_originales', to='rankingWaterpolo.categoria')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'equipos',
            },
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('usuario_id', models.IntegerField()),
                ('puntuacion', models.IntegerField(help_text='Puntuación del 1 al 10')),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='rankingWaterpolo.team')),
            ],
            options={
                'verbose_name': 'Valoración',
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='Mi Top 5', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rankingWaterpolo.categoria')),
                ('posicion_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_pos1', to='rankingWaterpolo.team')),
                ('posicion_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_pos2', to='rankingWaterpolo.team')),
                ('posicion_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_pos3', to='rankingWaterpolo.team')),
                ('posicion_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_pos4', to='rankingWaterpolo.team')),
                ('posicion_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_pos5', to='rankingWaterpolo.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='equipos',
            field=models.ManyToManyField(related_name='categorias_asignadas', to='rankingWaterpolo.Team'),
        ),
    ]
