# Generated by Django 4.1.13 on 2026-02-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('escudo', models.URLField(blank=True, max_length=500, null=True)),
                ('liga', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=20)),
                ('entrenador', models.CharField(max_length=100)),
                ('piscina', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'teams',
            },
        ),
    ]
